name: Refresh ECR docker password

on:
  # For manual dispatch
#  workflow_dispatch:
#  schedule:
    # Run every 8 hours
 #   - cron: '0 */8 * * *'
   push:
    branches:
      - 'main'
jobs:
  create-ecr-password:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get current ECR password
        id: ecr-password
        run: echo "::set-output name=password::$(aws ecr get-login-password)"

      - name: Save the ECR password secret
        id: save-secret
        uses: Skandalik/save-secret@v1.0.0
        with:
          github_token: ${{ secrets.GH_API_ACCESS_TOKEN }}
          secret_name: ECR_PASSWORD
          secret_value: ${{ steps.ecr-password.outputs.password }} 
      - name: Configure Kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.23.6'
        id: install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION}}
#          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}

      - name: Update KubeConfig
        shell: bash
        run: |
          aws eks update-kubeconfig --name ${{ secrets.AWS_CLUSTER_NAME }} --region=${{ secrets.AWS_REGION }}






#name: Run tests

#on:
#  push:
#    branches:
#      - 'main'

#jobs:
#  ecr_login:
 #   runs-on: ubuntu-latest
 #   outputs:
 #     ecr_password: ${{ steps.retrieve_password.outputs.ecr_password }}
 #   steps:
 #     - name: Set up AWS CLI
 #       uses: chrislennon/action-aws-cli@1.1
 #     - id: retrieve_password
 #       name: Retrieve ECR password and store as secret
 #       env:
 #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 #         AWS_DEFAULT_REGION: us-east-1
 #       run: echo "::set-output name=ecr_password::$(aws ecr get-login-password)"
